#pragma config(Sensor, dgtl1,  xAxis,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  xLimit,         sensorTouch)
#pragma config(Sensor, dgtl4,  yAxis,          sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  yLimit,         sensorTouch)
#pragma config(Sensor, dgtl7,  start,          sensorTouch)
#pragma config(Motor,  port1,           X,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Y,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int xSpeed = 63;
int ySpeed = 63;

void zeroEncoders(){
	SensorValue[xAxis] = 0;
	SensorValue[yAxis] = 0;
}

void goToZero(){
	while(SensorValue[xLimit] == 0){
		motor[X] = -xSpeed;
	}
	motor[X] = 0;

	while(SensorValue[yLimit] == 0){
		motor[Y] = -ySpeed;
	}
	motor[Y] = 0;
}

void drawBox(int x, int y){
	zeroEncoders();

	while(SensorValue[xAxis] <= x){
		motor[X] = xSpeed;
	}
	motor[X] = 0;

	while(SensorValue[yAxis] < y){
		motor[Y] = ySpeed;
	}
	motor[Y] = 0;

	while(SensorValue[xLimit] == 0){
		motor[X] = -xSpeed;
	}
	motor[X] = 0;

	while(SensorValue[yLimit] == 0){
		motor[Y] = -ySpeed;
	}
	motor[Y] = 0;

	drawBox(x-5, y-6);
}

task main(){
	if(SensorValue[start] == 1){
		if(SensorValue[xLimit] == 1 && SensorValue[yLimit] == 1){
				drawBox(100, 150);
		}
		goToZero();
	}
}
